spring.application.name=taskapi
spring.datasource.url=jdbc:postgresql://localhost:5432/javabot
spring.datasource.username=postgres
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true